void treeviewer() {
//=========Macro generated by ROOT version5.27/04
//=========for tree "TreeForTracks" (Sun Oct 16 13:43:02 2011)
//===This macro can be opened from a TreeViewer session after loading
//===the corresponding tree, or by running root with the macro name argument

   open_session();
}

open_session(void *p = 0) {
   gSystem->Load("libTreeViewer");
   TTreeViewer *treeview = (TTreeViewer *) p;
   if (!treeview) treeview = new TTreeViewer();
   TTree *tv_tree = (TTree*)gROOT->FindObject("TreeForTracks");
   TFile *tv_file = (TFile*)gROOT->GetListOfFiles()->FindObject("trackingInputSample.root");
   if (!tv_tree) {
      if (!tv_file) tv_file = new TFile("trackingInputSample.root");
      if (tv_file)  tv_tree = (TTree*)tv_file->Get("TreeForTracks");
      if(!tv_tree) {
         printf("Tree %s not found", fTree->GetName());
         return;
      }
   }

   treeview->SetTreeName("TreeForTracks");
   treeview->SetNexpressions(10);
//         Set expressions on axis and cut
   TTVLVEntry *item;
//   X expression
   item = treeview->ExpressionItem(0);
   item->SetExpression("pos[3]", "~pos[3]");
//   Y expression
   item = treeview->ExpressionItem(1);
   item->SetExpression("pos[5]", "~pos[5]");
//   Z expression
   item = treeview->ExpressionItem(2);
   item->SetExpression("", "-empty-");
//   Cut expression
   item = treeview->ExpressionItem(3);
   item->SetExpression("~nclg1 && ~nclg2 && ~nclg4", "~AllOneCls");
//         Scan list
   item = treeview->ExpressionItem(4);
   item->SetExpression("", "Scan box");
//         User defined expressions
   item = treeview->ExpressionItem(5);
   item->SetExpression("pos[0]", "~pos[0]", kFALSE);
   item = treeview->ExpressionItem(6);
   item->SetExpression("pos[1]", "~pos[1]", kFALSE);
   item = treeview->ExpressionItem(7);
   item->SetExpression("pos[2]", "~pos[2]", kFALSE);
   item = treeview->ExpressionItem(8);
   item->SetExpression("pos[3]", "~pos[3]", kFALSE);
   item = treeview->ExpressionItem(9);
   item->SetExpression("pos[4]", "~pos[4]", kFALSE);
   item = treeview->ExpressionItem(10);
   item->SetExpression("pos[5]", "~pos[5]", kFALSE);
   item = treeview->ExpressionItem(11);
   item->SetExpression("ncl[0]==ncl[1]==1", "~nclg1", kTRUE);
   item = treeview->ExpressionItem(12);
   item->SetExpression("ncl[2]==ncl[3]==1", "~nclg2", kTRUE);
   item = treeview->ExpressionItem(13);
   item->SetExpression("ncl[4]==ncl[5]==1", "~nclg4", kTRUE);
   item = treeview->ExpressionItem(14);
   item->SetExpression("~nclg1 && ~nclg2 && ~nclg4", "~AllOneCls", kTRUE);
//--- session object
   tv_session = new TTVSession(treeview);
   treeview->SetSession(tv_session);
//--- Connect first record
   tv_session->First();
}
